export const COMPETITION_CLASS = {
  name: "12A6",
  schoolYear: "2026-2027",
} as const;

// Danh sách được chép từ file Excel; chưa gán điểm giả.
export const ROSTER = [
  { name: "Yến Nhi", team: "Tổ 1" },
  { name: "Gia Kha", team: "Tổ 1" },
  { name: "Tấn Phát", team: "Tổ 1" },
  { name: "Quốc Hiệp", team: "Tổ 1" },
  { name: "Uyên Như", team: "Tổ 1" },
  { name: "Gia Kỳ", team: "Tổ 1" },
  { name: "Kim Ngân (PHT)", team: "Tổ 1" },
  { name: "Duy Khang", team: "Tổ 1" },
  { name: "Minh Hào", team: "Tổ 1" },
  { name: "Cát Tiên (TT)", team: "Tổ 1" },
  { name: "Trọng Ân", team: "Tổ 2" },
  { name: "Hoàng Anh", team: "Tổ 2" },
  { name: "Bảo Ngọc", team: "Tổ 2" },
  { name: "Ngọc Hoài", team: "Tổ 2" },
  { name: "Bảo Vi", team: "Tổ 2" },
  { name: "Tường Vy (TQ)", team: "Tổ 2" },
  { name: "Mạnh Thương", team: "Tổ 2" },
  { name: "Thành Danh", team: "Tổ 2" },
  { name: "Phương Thảo (LT)", team: "Tổ 2" },
  { name: "Quốc Huy (TT)", team: "Tổ 2" },
  { name: "Ngọc Hảo", team: "Tổ 3" },
  { name: "Ngọc Diệu", team: "Tổ 3" },
  { name: "Hà My", team: "Tổ 3" },
  { name: "Thảo Ngân", team: "Tổ 3" },
  { name: "Kim Hoa", team: "Tổ 3" },
  { name: "Gia Hân", team: "Tổ 3" },
  { name: "Nguyên Vũ", team: "Tổ 3" },
  { name: "Gia Bảo", team: "Tổ 3" },
  { name: "Hữu Tài (TT)", team: "Tổ 3" },
  { name: "Trọng Đức", team: "Tổ 4" },
  { name: "Mỹ Duyên", team: "Tổ 4" },
  { name: "Ngọc Như", team: "Tổ 4" },
  { name: "Phương Trâm", team: "Tổ 4" },
  { name: "Ngọc Trâm", team: "Tổ 4" },
  { name: "Anh Thư", team: "Tổ 4" },
  { name: "Trâm Anh (TT)", team: "Tổ 4" },
] as const;

export const POSITIVE_CATEGORIES = [
  "Phát biểu, xung phong lên bảng làm bài tập",
  "Điểm tốt (7, 8, 9, 10)",
  "Chủ động, trách nhiệm, tham gia, nhận nhiệm vụ",
] as const;

export const NEGATIVE_CATEGORIES = [
  "Không hoàn thành nhiệm vụ học tập/nhiệm vụ khác",
  "Nói chuyện, tự ý đổi chỗ ngồi",
  "Về giữa buổi có phép, vào tiết trễ",
  "Đi học trễ, vắng học có phép",
  "Vắng học không phép",
  "Vi phạm tác phong/đồng phục/phù hiệu",
  "Tập trung chậm giờ chào cờ (sau 6h55)",
  "Mang thức ăn, nước uống có màu vào lớp hoặc chất cấm",
  "Ngồi lên bàn/lan can; nói tục, chửi thề, xúc phạm bạn",
  "Gây gổ, đánh nhau",
  "Không mang sách vở khi đến lớp",
  "Xả rác bừa bãi",
  "Vi phạm quy định về tóc, móng, trang điểm, khuyên tai, xăm mình",
  "Sử dụng điện thoại khi chưa được giáo viên cho phép",
  "Vi phạm quy chế kiểm tra, thi cử",
  "Trộm cắp, phá hoại tài sản, đánh bài, hút thuốc",
] as const;
